version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/dat

volumes:
  postgres_data:
